# This section is used for any module communicating with an API Fortress Dashboard instance
dashboard:
  companyId: 1

# Engine settings
engine:
  secured: false
  synchronous:
    timeout: 10 seconds
    duration: 1 minute

# The core web server settings
webserver:
  active: true

downloader:
  location: Udine, My Home
  socket_timeout_millis: 2000
  connect_timeout_millis: 1000
  disable_ssl_validation: false

elastic:
  events:
    host: localhost
    port1: 9200
    port2: 9201
    scheme: http
    id: _id
  eventspost:
    host: localhost
    port1: 9200
    port2: 9201
    scheme: http
    id: _id
  metrics:
    host: localhost
    port1: 9200
    port2: 9201
    scheme: http
    id: _id
  metricspost:
    host: localhost
    port1: 9200
    port2: 9201
    scheme: http
    id: _id

filesystem:
  downloader:
    basepath: files/downloaders
  tests:
    basepath: files/tests
  vault:
    basepath: files/vault
  hooks:
    path: files/hooks.yml