# This section is used for any module communicating with an API Fortress Dashboard instance
dashboard:
  companyId: 1

# Engine settings
engine:
  secured: false
  synchronous:
    timeout: 10 seconds
    duration: 1 minute

# The core web server settings
webserver:
  active: true

downloader:
  location: Udine, My Home
  socket_timeout_millis: 2000
  connect_timeout_millis: 1000
  disable_ssl_validation: false

jdbc:
  downloader:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    properties:
      user: postgres
      password: docker
    table: downloader
  events:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    properties:
      user: postgres
      password: docker
    table: events
  metrics:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    properties:
      user: postgres
      password: docker
    table: metrics
  tests:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    properties:
      user: postgres
      password: docker
    table: tests
  vault:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    properties:
      user: postgres
      password: docker
    table: vault
  hooks:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    properties:
      user: postgres
      password: docker
    table: hooks

filesystem:
  hooks:
    path: files/hooks.yml